GET  http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcwODcwMTcyNCwiZXhwIjoxNzA4NzAxNzM5fQ.5pYomB2j5hGvg6XnjEM5E0syY8MQplr29DOZqiTaYz4

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcwODcwMzA3Nn0.Kt9BUZh9M_lZu-nSHklt-XYXA3ydI84UtzYygLatr7M"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcwODcwMjk5OH0.E5Js-rxFjqQ2aouyA9Agy22i6OwKLLGk9jXeH_LbCGE"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}